/*
	*	Original script by: Shafiul Azam
	*	Version 4.0
	*	Modified by: Luigi Balzano

	*	Description:
	*	Inserts Countries and/or States as Dropdown List
	*	How to Use:

		In Head section:
		----------------
		<script type= "text/javascript" src = "countries.js"></script>
		
		In Body Section:
		----------------
		Select Country (with states):   <select id="country" name ="country"></select>
			
		Select State: <select name ="state" id ="state"></select>

        Select Country (without states):   <select id="country2" name ="country2"></select>
			
		<script language="javascript">
			populateCountries("country", "state");
			populateCountries("country2");
		</script>

	*
	*	License: Free to copy, distribute, modify, whatever you want to.
	*	Aurthor's Website: http://bdhacker.wordpress.com
	*
*/

// Countries
//var country_arr = new Array("ANDAMAN AND NICOBAR ISLAND", "ANDHRA PRADESH", "ARUNACHAL PRADESH", "ASSAM", "BIHAR", "CHANDIGARH", "CHHATTISGARH", "DADRA AND NAGAR HAVELI", "DAMAN AND DIU", "DELHI", "GOA", "GUJARAT", "HARYANA", "HIMACHAL PRADESH", "JAMMU AND KASHMIR", "JHARKHAND", "KARNATAKA", "KERALA", "LAKSHADWEEP", "MADHYA PRADESH", "MAHARASHTRA", "MANIPUR", "MEGHALAYA", "MIZORAM", "NAGALAND", "ODISHA", "PUDUCHERRY", "PUNJAB", "RAJASTHAN", "SIKKIM", "TAMIL NADU", "TELANGANA", "TRIPURA", "UTTAR PRADESH", "UTTARAKHAND", "WEST BENGAL");
var country_arr = new Array("ANDHRA PRADESH");

// States
var s_a = new Array();
s_a[1]="ANANTAPUR|CHITTOOR|EAST GODAVARI|GUNTUR|KADAPA|KRISHNA|KURNOOL|NELLORE|PRAKASAM|SRIKAKULAM|VISAKHAPATNAM|VIZIANAGARAM|WEST GODAVARI";

/*s_a[0]="";
s_a[1]="NICOBAR|NORTH AND MIDDLE ANDAMAN|SOUTH ANDAMAN";
s_a[2]="ANANTAPUR|CHITTOOR|EAST GODAVARI|GUNTUR|KADAPA|KRISHNA|KURNOOL|NELLORE|PRAKASAM|SRIKAKULAM|VISAKHAPATNAM|VIZIANAGARAM|WEST GODAVARI";
s_a[3]="BAKSA|BARPETA|BONGAIGAON|CACHAR|CHIRANG|DARRANG|DHEMAJI|DHUBRI|DIBRUGARH|DIMA HASAO|GOALPARA|HAILAKANDI|JORHAT|KAMRUP METROPOLITAN|KAMRUP|KARBI ANGLONG|KARIMGANJ|KOKRAJHAR|LAKHIMPUR|MORIGAON|NAGAON|NALBARI|SIVASAGAR|SONITPUR|TINSUKIA|UDALGURI";
s_a[4]="ANJAW|CHANGLANG|DIBANG VALLEY|EAST KAMENG|EAST SIANG|KURUNG KUMEY|LOHIT|LOWER DIBANG VALLEY|LOWER SUBANSIRI|PAPUM PARE|TAWANG|TIRAP|UPPER SIANG|UPPER SUBANSIRI|WEST KAMENG|WEST SIANG";
s_a[5]="ARARIA|ARWAL|AURANGABAD|BANKA|BEGUSARAI|BHAGALPUR|BHOJPUR|BUXAR|DARBHANGA|EAST CHAMPARAN (MOTIHARI)|GAYA|GOPALGANJ|JAMUI|JEHANABAD|KAIMUR (BHABUA)|KATIHAR|KHAGARIA|KISHANGANJ|LAKHISARAI|MADHEPURA|MADHUBANI|MUNGER (MONGHYR)|MUZAFFARPUR|NALANDA|NAWADA|PATNA|PURNIA (PURNEA)|ROHTAS|SAHARSA|SAMASTIPUR|SARAN|SHEIKHPURA|SHEOHAR|SITAMARHI|SIWAN|SUPAULVAISHALI|WEST CHAMPARAN";
s_a[6]="CHANDIGARH";
s_a[7]="BIJAPUR|BILASPUR|DANTEWADA (SOUTH BASTAR)|DHAMTARI|DURG|JANJGIR-CHAMPA|JANJGIR-CHAMPA|JASHPUR|KABIRDHAM (KAWARDHA)|KANKER (NORTH BASTAR)|KORBA|KOREA (KORIYA)|MAHASAMUND|NARAYANPUR|RAIGARH|RAIPUR|RAJNANDGAON|SURGUJA";
s_a[8]="DADRA & NAGAR HAVELI";
s_a[9]="DAMAN|DIU";
s_a[10]="CENTRAL DELHI|EAST DELHI|NEW DELHI|NORTH DELHI NORTH EAST DELHI|NORTH WEST DELHI|SOUTH DELHI|SOUTH WEST DELHI";
s_a[11]="NORTH GOA|SOUTH GOA";
s_a[12]="AHMEDABAD|AMRELI|ANAND|BANASKANTHA (PALANPUR)|BHARUCH|BHAVNAGAR|DAHOD|DANGS (AHWA)|GANDHINAGAR|JAMNAGAR|JUNAGADH|KACHCHH|KHEDA (NADIAD)|MEHSANA|NARMADA (RAJPIPLA)|NAVSARI|PANCHMAHAL (GODHRA)|PATAN|PORBANDAR|RAJKOT|SABARKANTHA (HIMMATNAGAR)|SURAT|SURENDRANAGAR|TAPI (VYARA)|VADODARA|VALSAD";
s_a[13]="AMBALA|BHIWANI|FARIDABAD|FATEHABAD|GURGAON|HISAR|JHAJJAR|JIND|KAITHAL|KARNAL|KURUKSHETRA|MAHENDRAGARH|MEWAT|PALWAL|PANCHKULA||PANIPAT|REWARI|ROHTAK|SIRSA|SONIPAT|YAMUNANAGAR";
s_a[14]="BILASPUR|CHAMBA|HAMIRPUR|KANGRA|KINNAUR|LAHAUL & SPITI|MANDI|SHIMLA|SIRMAUR (SIRMOUR)|SOLAN|UNA";
s_a[15]="ANANTNAG|BARAMULLA|BUDGAM|DODA|GANDERBAL|JAMMU|KARGIL|KATHUA|KISHTWAR|KULGAM|KUPWARA|LEH|POONCH|PULWAMA|RAJOURI|RAMBAN|REASI|SAMBA|SHOPIAN|SRINAGAR|UDHAMPUR";
s_a[16]="BOKARO|CHATRA|DEOGHAR|DHANBAD|DUMKA|EAST SINGHBHUM|GARHWA|GIRIDIH|GODDA|GUMLA|HAZARIBAG|JAMTARA|KHUNTI|KODERMA|LATEHAR|LOHARDAGA|PAKUR|PALAMU|RAMGARH|RANCHI|SAHIBGANJ|SERAIKELA-KHARSAWAN|SIMDEGA";
s_a[17]="BAGALKOT|BAGALKOT|BANGALORE RURAL|BANGALORE URBAN|BELGAUM|BELLARY|BIDAR|BIJAPUR|CHAMARAJANAGAR|CHICKMAGALUR|CHIKBALLAPUR|CHITRADURGA|DAKSHINA KANNADA|DAVANGERE|DHARWAD|GADAG|GULBARGA| HASSAN|HAVERI|KODAGU|KOLAR|KOPPAL|MANDYA|MYSORE|RAICHUR|RAMNAGARA|SHIMOGA|TUMKUR|UDUPI|UTTARA KANNADA (KARWAR)|YADGIR";
s_a[18]="ALAPPUZHA|ERNAKULAM|IDUKKI|KANNUR|KASARAGOD|KOLLAM|KOTTAYAM|KOZHIKODE|MALAPPURAM|PALAKKAD|PATHANAMTHITTA|THIRUVANANTHAPURAM|THRISSUR|WAYANAD";
s_a[19]="LAKSHADWEEP";
s_a[20]="ALIRAJPUR|ANUPPUR|ASHOKNAGAR|BALAGHAT|BARWANI|BETUL|BHIND|BHOPAL|BURHANPUR|CHHATARPUR|CHHINDWARA|DAMOH|DATIA|DEWAS|DHAR|DINDORI|GUNA|GWALIOR|HARDA|HOSHANGABAD|INDORE|JABALPUR|JHABUA|KATNI|KHANDWA|KHARGONE|MANDLA|MANDSAUR|MORENA|NARSINGHPUR|NEEMUCH|PANNA|RAISEN|RAJGARH|RATLAM|REWA|SAGAR|SATNA|SEHORE|SEONI|SHAHDOL|SHAJAPUR|SHEOPUR|SHIVPURI|SIDHI|SINGRAULI|TIKAMGARH|UJJAIN|UMARIA|VIDISHA";
s_a[21]="AHMEDNAGAR|AKOLA|AMRAVATI|AURANGABAD|BEED|BULDHANA|CHANDRAPUR|DHULE|GADCHIROLI|GONDIA|HINGOLI|JALGAON|JALNA|KOLHAPUR|LATUR|NAGPUR|NANDED|NANDURBAR|NASHIK|OSMANABAD|PARBHANIPUNE|RAIGAD|RATNAGIRI|SANGLI|SATARA|SINDHUDURG|SOLAPUR|THANE|WARDHA|WASHIM|YAVATMAL";
s_a[22]="BISHNUPUR|CHANDEL|CHURACHANDPUR|IMPHAL EAST|IMPHAL WEST| SENAPATI|TAMENGLONG|THOUBAL|UKHRUL";
s_a[23]="EAST GARO HILLS|EAST KHASI HILLS|RI BHOI|SOUTH GARO HILLS|WEST GARO HILLS|WEST KHASI HILLS";
s_a[24]="AIZAWL|CHAMPHAI|KOLASIB|LAWNGTLAI|LUNGLEI|MAMIT|SAIHA|SERCHHIP";
s_a[25]="DIMAPUR|KIPHIRE|KOHIMA|LONGLENG|MOKOKCHUNG|MON|PEREN|PHEK|TUENSANG|WOKHA|ZUNHEBOTO";
s_a[26]="ANGUL|BALANGIR|BALASORE|BARGARH|BHADRAK|BOUDH|CUTTACK|DEOGARH|DHENKANAL|GAJAPATI|GANJAM|JAGATSINGHAPUR|JAJPUR|JHARSUGUDA|KALAHANDI|KANDHAMAL|KENDRAPARA|KENDUJHAR (KEONJHAR)|KHORDHA|KORAPUT|MALKANGIRI|MAYURBHANJ|NABARANGPUR|NAYAGARH|NUAPADA|PURI|RAYAGADA|SAMBALPUR|SONEPUR|SUNDARGARH";
s_a[27]="KARAIKAL|MAHE|PONDICHERRY|YANAM";
s_a[28]="AMRITSAR|BARNALA|BATHINDA|FARIDKOT|FATEHGARH SAHIB|FEROZEPUR|GURDASPUR|HOSHIARPUR|JALANDHAR|KAPURTHALA|LUDHIANA|MANSA|MOGA|MUKTSAR|PATIALA|RUPNAGAR|SANGRUR|SAS NAGAR (MOHALI)|TARN TARAN";
s_a[29]="AJMER|ALWAR|BARAN|BARMER|BHARATPUR|BHILWARA|BIKANER|BUNDI|CHITTORGARH|CHURU|DAUSA|DUNGARPUR|HANUMANGARH|JAIPUR|JAISALMER|JALORE|JHALAWAR|JHUNJHUNU|JODHPUR|KARAULI|NAGAUR|PALI|PRATAPGARH|RAJSAMAND|SAWAI MADHOPUR|SIKAR|SIROHI|SRI GANGANAGAR|TONK";
s_a[30]="EAST SIKKIM|NORTH SIKKIM|WEST SIKKIM";
s_a[31]="ARIYALUR|CHENNAI|COIMBATORE|CUDDALORE|DHARMAPURI|DINDIGUL|ERODE|KANCHIPURAM|KANYAKUMARI|KARUR|KRISHNAGIRI|MADURAI|NAGAPATTINAM|NAMAKKAL|NILGIRIS|PERAMBALUR|PUDUKKOTTAI|RAMANATHAPURAM|SALEM|SIVAGANGA|THANJAVUR|THENI|THOOTHUKUDI (TUTICORIN)|TIRUCHIRAPPALLI|TIRUNELVELI|TIRUPPUR|TIRUVALLUR|TIRUVANNAMALAI|TIRUVARUR|VELLORE|VILUPPURAM|VIRUDHUNAGAR";
s_a[32]="ADILABAD|BADRADRI KOTHAGUDEM|HYDERABAD|JAGITHYAL|JANAGAON|JAYASHENKAR BHUPALPALLY|JOGULAMBA GADWAL|KAMAREDDY|KARIMNAGAR|KHAMMAM|KOMURAM BEEM|MAHABUBABAD|MAHBUBNAGAR|MANCHIRYAL|MEDAK|MEDCHAL|NAGAR KURNOOL|NALGONDA|NIRMAL|NIZAMABAD|PEDDAPELLI|RAJANNA SIRICILLA|RANGA REDDY|SANGA REDDY|SIDDIPET|SURYAPET|VIKARABAD|WANAPARTHY|WARANGAL(RURAL)|WARANGAL(URBAN)|YADADRI BHUVANAGIRI";
s_a[33]="DHALAI|NORTH TRIPURA|SOUTH TRIPURA|WEST TRIPURA";
s_a[34]="AGRA|ALIGARH|ALLAHABAD|AMBEDKAR NAGAR|AURAIYA|AZAMGARH|BAGHPAT|BAHRAICH|BALLIA|BALRAMPUR|BANDA|BARABANKI|BAREILLY|BASTI|BIJNOR|BUDAUN|BULANDSHAHR|CHANDAULI|CHITRAKOOT|DEORIA|ETAH|ETAWAH|FAIZABAD|FARRUKHABAD|FATEHPUR|FIROZABAD|GAUTAM BUDDHA NAGAR|GHAZIABAD|GHAZIPUR|GONDA|GORAKHPUR|HAMIRPUR|HARDOI|JALAUN|JAUNPUR|JHANSI|JYOTIBA PHULE NAGAR (J.P. NAGAR)|KANNAUJ|KANPUR DEHAT|KANPUR NAGAR|KANSHIRAM NAGAR (KASGANJ) KAUSHAMBI|KUSHINAGAR (PADRAUNA)|LAKHIMPUR - KHERI|LALITPUR|LUCKNOW|MAHARAJGANJ|MAHOBA|MAINPURI|MATHURA|MAU|MEERUT|MIRZAPUR|MORADABAD|MUZAFFARNAGAR|PANCHSHEEL NAGAR|PILIBHIT|PRABUDDH NAGAR|PRATAPGARH|RAEBARELI|RAMPUR|SAHARANPUR|SANT KABIR NAGAR|SANT RAVIDAS NAGAR SHAHJAHANPUR|SHRAVASTI|SIDDHARTH NAGAR|SITAPUR|SONBHADRA|UNNAO|VARANASI";
s_a[35]="ALMORA|BAGESHWAR|CHAMOLI|CHAMPAWAT|DEHRADUN|HARIDWAR|NAINITAL|PAURI GARHWAL|PITHORAGARH|RUDRAPRAYAG|TEHRI GARHWAL|UDHAM SINGH NAGAR|UTTARKASHI";
s_a[36]="BANKURA|BIRBHUM|BURDWAN (BARDHAMAN)|COOCH BEHAR|DAKSHIN DINAJPUR (SOUTH DINAJPUR)|DARJEELING|HOOGHLY|HOWRAH|JALPAIGURI|MALDA|MURSHIDABAD|NADIA|NORTH 24 PARGANAS|PASCHIM MEDINIPUR (WEST MEDINIPUR)|PURBA MEDINIPUR (EAST MEDINIPUR)|PURULIA|SOUTH 24 PARGANAS|UTTAR DINAJPUR (NORTH DINAJPUR)";

*/

function populateStates( countryElementId, stateElementId ){
	var selectedCountryIndex = document.getElementById( countryElementId ).selectedIndex;

	var stateElement = document.getElementById( stateElementId );
	
	stateElement.length=0;	// Fixed by Julian Woods
	stateElement.options[0] = new Option('Select District','');
	stateElement.selectedIndex = 0;
	
	var state_arr = s_a[selectedCountryIndex].split("|");
	
	for (var i=0; i<state_arr.length; i++) {
		stateElement.options[stateElement.length] = new Option(state_arr[i],state_arr[i]);
	}
}

function populateCountries(countryElementId, stateElementId){
	// given the id of the <select> tag as function argument, it inserts <option> tags
	var countryElement = document.getElementById(countryElementId);
	countryElement.length=0;
	countryElement.options[0] = new Option('Select State','-1');
	countryElement.selectedIndex = 0;
	for (var i=0; i<country_arr.length; i++) {
		countryElement.options[countryElement.length] = new Option(country_arr[i],country_arr[i]);
	}

	// Assigned all countries. Now assign event listener for the states.

	if( stateElementId ){
		countryElement.onchange = function(){
			populateStates( countryElementId, stateElementId );
		};
	}
}